######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 10 16:36:59 2017
######################################################################

QT -= gui
QT += network

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Client.h
SOURCES += Client.cpp main.cpp
