######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 18 16:46:10 2016
######################################################################

# TEMPLATE = app
CONFIG += qt
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT = core network xml

# Input
SOURCES += main.cpp
