######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 2 15:17:23 2018
######################################################################

QT -= gui
QT += core
QT += xml

TEMPLATE = app
TARGET = readXml
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += XmlHandler.h
SOURCES += main.cpp XmlHandler.cpp
