######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 19 12:22:06 2015
######################################################################

TEMPLATE = app
TARGET = bug
DEPENDPATH += .
INCLUDEPATH += .

QT -= gui
QT += xml

# Input
SOURCES += bug.cpp
