######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 2 11:39:24 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += rgbSliders.ui
HEADERS += RgbSliderWidget.h
SOURCES += main.cpp RgbSliderWidget.cpp
