######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 25 13:04:33 2015
######################################################################

QT -= gui
QT += network
QT += xml

TEMPLATE = app
CONFIG += qt
TARGET = echo
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += server.h XmlHandler.h
SOURCES += main.cpp server.cpp XmlHandler.cpp



