######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 3 11:02:23 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += centralwidget.h mainwindow.h
SOURCES += centralwidget.cpp main.cpp mainwindow.cpp
