######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 28 13:20:43 2016
######################################################################

QT += widgets

TEMPLATE = app
TARGET = dialog
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += StartTestDialog.h
SOURCES += main.cpp StartTestDialog.cpp
