######################################################################
# Automatically generated by qmake (3.0) Wed Apr 13 16:34:26 2022
######################################################################

QT += widgets

TEMPLATE = app
TARGET = mw
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
