######################################################################
# Automatically generated by qmake (3.1) Fri May 13 17:14:49 2022
######################################################################

TEMPLATE = app
TARGET = charts
INCLUDEPATH += .
DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x050702

QT += widgets charts

HEADERS += MainWindow.h
FORMS += MainWindow.ui
SOURCES += main.cpp MainWindow.cpp
