######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 25 13:04:33 2015
######################################################################

TEMPLATE = app
CONFIG += qt
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += server.h
SOURCES += main.cpp server.cpp


QT += network

