######################################################################
# Automatically generated by qmake (3.0) Mon May 2 15:24:06 2022
######################################################################

QT += widgets
QT += serialport

TEMPLATE = app
TARGET = combobox
INCLUDEPATH += .

# Input
HEADERS += CentralWidget.h MainWindow.h
FORMS += CentralWidget.ui MainWindow.ui
SOURCES += CentralWidget.cpp MainWindow.cpp main.cpp
