######################################################################
# Automatically generated by qmake (3.0) Sun Apr 17 12:32:28 2022
######################################################################

TEMPLATE = app
TARGET = gps
INCLUDEPATH += .
QT += widgets
QT += serialport

# Input
FORMS += BasicDisplay.ui
HEADERS += GpsReceiver.h MessageDecoder.h BasicDisplay.h
SOURCES += GpsReceiver.cpp MessageDecoder.cpp BasicDisplay.cpp main.cpp
