######################################################################
# Automatically generated by qmake (3.0) Sun Jan 6 11:24:32 2019
######################################################################

QT -= gui
QT += serialport

TEMPLATE = app
TARGET = gps
INCLUDEPATH += .

# Input
HEADERS += GpsReceiver.h
SOURCES += GpsReceiver.cpp main.cpp
